export const LOGIN_LOADING="LOGIN_LOADING";
export const LOGIN_SUCCES="LOGIN_SUCCES";
export const LOGIN_ERROR="LOGIN_ERROR";
export const USER_TODO="USER_TODO";

export const LOGOUT_SUCCESS="LOGOUT_SUCCESS"